######################################################################
# Automatically generated by qmake (2.01a) Thu Jun 4 08:01:07 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += anet.h CurlHttpGet.h fmacros.h redisclient.h
SOURCES += anet.c CurlHttpGet.cpp test_client.cpp
